services:
  postgres:
    image: 'postgres:15.8@sha256:0836104ba0de8d09e8d54e2d6a28389fbce9c0f4fe08f4aa065940452ec61c30'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      APP_DB_NAME: 'ngc'
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
  redis:
    image: 'redis:7.4.2@sha256:93a8d83b707d0d6a1b9186edecca2e37f83722ae0e398aee4eea0ff17c2fad0e
    ports:
      - '6379:6379'
