export const ATTRIBUTE_IS_ORGANISATION_ADMIN = 'IS_ORGANISATION_ADMIN'
export const ATTRIBUTE_ORGANISATION_NAME = 'ORGANISATION_NAME'
export const ATTRIBUTE_ORGANISATION_SLUG = 'ORGANISATION_SLUG'
export const ATTRIBUTE_LAST_POLL_PARTICIPANTS_NUMBER =
  'LAST_POLL_PARTICIPANTS_NUMBER'
export const ATTRIBUTE_USER_ID = 'USER_ID'
export const ATTRIBUTE_PRENOM = 'PRENOM'
export const ATTRIBUTE_OPT_IN = 'OPT_IN'
export const ATTRIBUTE_LAST_SIMULATION_DATE = 'LAST_SIMULATION_DATE'

// List IDs
export const LIST_ID_ORGANISATIONS = 27
