export enum TemplateIds {
  SIMULATION_COMPLETED = 55,
  VERIFICATION_CODE = 66,
  ORGANISATION_CREATED = 70,
  SIMULATION_IN_PROGRESS = 102,
}

export enum Attributes {
  LAST_POLL_PARTICIPANTS_NUMBER = 'LAST_POLL_PARTICIPANTS_NUMBER',
  IS_ORGANISATION_ADMIN = 'IS_ORGANISATION_ADMIN',
  ORGANISATION_NAME = 'ORGANISATION_NAME',
  ORGANISATION_SLUG = 'ORGANISATION_SLUG',
  USER_ID = 'USER_ID',
  PRENOM = 'PRENOM',
  OPT_IN = 'OPT_IN',
}
