name: Artillery Load Test

on:
  workflow_dispatch:

jobs:
  artillery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies with Yarn
        uses: borales/actions-yarn@v4
        with:
          cmd: install # Exécute `yarn install`

      - name: Execute spike load tests
        uses: artilleryio/action-cli@v1
        with:
          command: run tests/load/spike-test.yml
