name: Artillery Load Test

on:
  workflow_dispatch:

jobs:
  artillery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Execute spike load tests
        uses: artilleryio/action-cli@v1
        with:
          command: run tests/load/spike-test.yml
